config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :controllers => { :registrations => "registrations", :sessions => "sessions",omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, :only => [:edit, :update, :index] do
    resources :conversations, :only => :index
    get 'notifications'
    post 'upload_file'
    collection do
      post 'autocomplete'
    end
    resources :subscriptions, :only => [:create,:destroy,:index]
  end

  resources :comments, :only => [:create, :destroy]

  resources :game_improvements, :only => [:create, :destroy, :show]
  resources :games do
    resources :game_boards

  end

  resources :votes, :only => [] do
    collection do
      post 'up'
      post 'down'
    end
  end

  resources :board_suggestions, :only => [:create,:destroy, :show]
  resources :invitations, :only => [] do
    collection do
      post 'check'
    end
  end

  resources :game_boards do
    collection do
      get 'popular'
      get 'archives'
    end
  end

  resources :workspaces

  resources :posts do
    post 'create_or_destroy_reaction'
    post 'flag_vote'
    collection do
      get 'popular'
      get 'familiar'
      get 'subscriptions'
      get 'user_games'
      get 'flagged'
      get 'autocomplete_tag_search'
    end
    member do
      post 'create_or_destroy_reaction'
    end
  end

  resources :conversations, :only => [:create,:show,:index, :destroy] do
    resources :messages, :only => [:create]
  end

  root 'pages#home'
  get '/pages/:page_name' => 'pages#index', :as => :pages
  get '/posts/:category/:tag' => 'posts#index', :as => :filtered_posts
  get '/sitemap.xml' => 'pages#sitemap'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/search' => 'users#search', via: [:get]
  # This needs to stay at the bottom such that a user can't override a preset URL
  match '/:display_name', :controller => :users, :action => :show, :as => :profile, via: [:get]
  get "/stats/:type", :as => 'stats', :controller => :stats, :action => :index


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :json, :html
  def create
    @comment_hash = params[:comment]
    @obj = @comment_hash[:commentable_type].constantize.find(@comment_hash[:commentable_id])
    # Not implemented: check to see whether the user has permission to create a comment on this object
    @comment = Comment.build_from(@obj, current_user.id, @comment_hash[:body])
    if @comment.save
      render :partial => "show_comment", :locals => { :comment => @comment }, :layout => false, :status => :created

    else
      render :js => "alert('error saving comment');"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy

    else
      render :js => "alert('error deleting comment');"
    end
  end

  def update
    @comment = Comment.find params[:id]

    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.html { redirect_to(@comment, :notice => 'User was successfully updated.') }
        format.json { respond_with_bip(@comment) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@comment) }
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/views/comments/_comment.html.haml
/ COMMENT
.comment[comment]
  %section.top
    %h6.byline
      =link_to user_path(comment.user) do
        %i.icon>
        =comment.user.username
        -if comment.user == current_user
          %span.label owner
      %small
        said
        %span.data
          = comment.created_at.strftime("%B %d, %Y at %l:%M %p")
  %section.content
    = comment.body
  %section.actions
    %ul.inline-list
      -if user_signed_in? && comment.user == current_user
        %li
          =link_to comment_path(comment), :method => :delete, :remote => :true do
            Delete


      %li
        %a{:href => "#"} Reply
/

app/views/comments/_comment_with_link.html.haml
/ COMMENT
.comment[comment]
  %section
    =link_to comment.commentable.body.truncate(20,'...'), post_path(comment.commentable_id)
  %section.top
    %h6.byline
      =link_to user_path(comment.user) do
        %i.icon>
        =comment.user.email
        -if comment.user == current_user
          %span.label Post Author
      %small
        said
        %span.data
          = comment.created_at.strftime("%B %d, %Y at %l:%M %p")
  %section.content
    = comment.body
  %section.actions
    %ul.inline-list
      -if user_signed_in? && comment.user == current_user
        %li
          =link_to comment_path(comment), :method => :delete, :remote => :true do
            Delete


      %li
        %a{:href => "#"} Reply
/

app/views/comments/_form.html.haml
.comment-form
	#new-comment
		= form_for comment, :remote => true do |f|
			= f.text_area :body, :label => false, :class => "input-field", :id => "comment-text"
			= f.hidden_field :commentable_id, :value => comment.commentable_id
			= f.hidden_field :commentable_type, :value => comment.commentable_type
			= f.submit "comment", :class => "button tiny", :disable_with => "Submitting…"

app/views/comments/_show_comment.js.haml
$('.comments').append("#{escape_javascript render @comment}");
$('.comment-form .input-field').val('');

app/views/comments/_show_comment_on_request.js.haml
$('#request_#{@obj.id} .comments').append("#{escape_javascript render @comment}");
$('.comment-form .input-field').val('');

app/views/comments/destroy.js.haml
$('#comment_#{@comment.id}').remove();

app/views/comments/index.html.haml
#new
  %button new comment
=render @comments


:javascript
  $(document).on('ready page:load', function(){
    $("#new-item").html("#{escape_javascript render :partial => 'comments/form'}");
    $('#new').on("click", function() {
      $('#new-item').foundation("reveal","open");
    });


  });