config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :controllers => { :registrations => "registrations", :sessions => "sessions",omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, :only => [:edit, :update, :index] do
    resources :conversations, :only => :index
    get 'notifications'
    post 'upload_file'
    collection do
      post 'autocomplete'
    end
    resources :subscriptions, :only => [:create,:destroy,:index]
  end

  resources :comments, :only => [:create, :destroy]

  resources :game_improvements, :only => [:create, :destroy, :show]
  resources :games do
    resources :game_boards

  end

  resources :votes, :only => [] do
    collection do
      post 'up'
      post 'down'
    end
  end

  resources :board_suggestions, :only => [:create,:destroy, :show]
  resources :invitations, :only => [] do
    collection do
      post 'check'
    end
  end

  resources :game_boards do
    collection do
      get 'popular'
      get 'archives'
    end
  end

  resources :workspaces

  resources :posts do
    post 'create_or_destroy_reaction'
    post 'flag_vote'
    collection do
      get 'popular'
      get 'familiar'
      get 'subscriptions'
      get 'user_games'
      get 'flagged'
      get 'autocomplete_tag_search'
    end
    member do
      post 'create_or_destroy_reaction'
    end
  end

  resources :conversations, :only => [:create,:show,:index, :destroy] do
    resources :messages, :only => [:create]
  end

  root 'pages#home'
  get '/pages/:page_name' => 'pages#index', :as => :pages
  get '/posts/:category/:tag' => 'posts#index', :as => :filtered_posts
  get '/sitemap.xml' => 'pages#sitemap'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/search' => 'users#search', via: [:get]
  # This needs to stay at the bottom such that a user can't override a preset URL
  match '/:display_name', :controller => :users, :action => :show, :as => :profile, via: [:get]
  get "/stats/:type", :as => 'stats', :controller => :stats, :action => :index


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  #before_destroy :delete_all_message_notifications
  #after_create :notify_item_owner, :if => Proc.new{ self.item != nil }


  belongs_to :user
  #belongs_to :item
  has_many :messages, :class_name => "Message", :dependent => :delete_all
  #has_many :notifications, :as => :notifier, :dependent => :delete_all
  #has_many :message_notifications, :through => :messages, :source => :notifications

  #validates :user_id, :exclusion => { :in => lambda { |conversation|
    #[Item.find(conversation.item_id).user_id]
  #}, :message => "You cannot message yourself about your own item." }, :unless => "item.nil?"

  #validate :item_type_is_allowed
  scope :from_user, lambda { |user| where(user_id: user.id) }
  scope :for_user, lambda { |user| where(recipient_id: user.id) }
  #scope :for_user_message, lambda{ |user| {:joins => :notifications, :conditions => ["receiver_id = ? and offers.item_id is null", user.id]}}

  def unread_message_count(usr)
    unread_message_count ||= Message.where("conversation_id = ? and user_id != ?", self.id, usr.id).count
  end
=begin
  private

  def delete_all_message_notifications
    Notification.delete_all(:id => self.message_notifications.collect(&:id))
  end

  def item_type_is_allowed
    #errors.add(:item, "type not allowed") unless item.allows_offers?
    true
  end

  def notify_item_owner
    notification = Notification.new
    notification.notifier = self
    notification.sender = self.user
    notification.receiver = self.item.user
    notification.save
  end

  def self.count_by_day(cutoff_at)
    result = count(:all, :conditions => ["created_at >= ?", cutoff_at],
                         :group => "DATE(created_at)")
    # See http://ruby-doc.org/core-1.8.7/classes/Hash.html#M000163
    result.default = 0
    result
  end
=end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  #before_filter :authenticate_user!
  before_filter :load_resource, :only => :destroy
  #authorize_resource :only => :destroy

  def create
    if params[:item_id]
      #recipient_id = Item.find(item_id_from_slug(params[:item_id])).user.id
      #conversation = Conversation.create(:item_id => item_id_from_slug(params[:item_id]), :user => current_user, :recipient_id => recipient_id)
      #Message.create(:conversation_id => conversation.id, :user => current_user, :body => params[:text])

    else
      conversation = Conversation.where(:user_id => current_user.id, :recipient_id => params[:user_id]).first
      if conversation.blank?
        conversation = Conversation.where(:user_id => params[:user_id], :recipient_id => current_user.id).first
        if conversation.blank?
          conversation = Conversation.create(:user => current_user, :recipient_id => params[:user_id])
        end
      end


      message = Message.create(:conversation_id => conversation.id, :user => current_user, :body => params[:text])
    end


    flash[:notice] = "message sent"
    redirect_to :back
  end

  def index
    # nested within items
    if params[:item_id].present?
      load_and_authorize_conversation
      render :partial => 'conversation', :layout => false

    # nested within users
    else
      load_all_conversations_for_current_user
      puts "loading"
    end
    if params[:conversation_id].present?
      @loaded_conversation = Conversation.find(params[:conversation_id]).includes(:messages, :item, :user)
    else
      @loaded_conversation = @conversations.first
    end

  end

  def show
    @conversation = Conversation.find(params[:id])
    respond_to do |format|
      format.js {render 'show', :locals => {conversation: @conversation}}
    end
  end
  
  def broadcast
    if current_user.is_admin?

    else
      redirect_to :home
    end
  end
  
  def send_broadcast
    if current_user.is_admin?
      conversation = Conversation.create(:user => current_user, :recipient_id => "-1")
      Message.create(:conversation_id => conversation.id, :user => current_user, :body => params[:text])
      flash[:notice] = "message sent"
      redirect_to :back
    else
      redirect_to :home
    end
  end

  def destroy
    @conversation.destroy
    redirect_to :back
  end
=begin  
  def search
    load_all_conversations_for_current_user
    messages = @conversations.map{|m| m.id}
    message_search = Message.search do
      fulltext params[:term]
      with :conversation_id, messages
    end
    results = message_search.results.first(10)
    unless results.nil?
      respond_to do |format|
        format.json { render :json => results.collect{|r| {:id => r.id,:value => r.search_excerpt(params[:term]), :path => conversation_path(r.conversation_id)}} }
      end
    end
  end
=end  
  

private

  def load_resource
    @conversation = Conversation.find(params[:id])
  end

  def load_and_authorize_conversation
    user_id = params[:user_id] || current_user.id
    @conversation = Conversation.find(:user_id => user_id)

    #authorize! :read, @conversation
  end

  def load_all_conversations_for_current_user
    user_id = current_user.id
    @conversations = (Conversation.includes(:messages).from_user(current_user) + Conversation.includes(:messages).for_user(current_user) + Conversation.includes(:messages).where(:recipient_id => "-1")).sort{|a,b| b.messages.first.created_at <=> a.messages.first.created_at }
    #@conversations = (Conversation.includes(:messages, :item).for_user_message(current_user) + Conversation.includes(:messages, :item).from_user(current_user) + Conversation.includes(:messages, :item).for_user(current_user) + Conversation.includes(:messages, :item).where(:recipient_id => "-1")).sort{|a,b| b.messages.first.created_at <=> a.messages.first.created_at }
    @conversations = @conversations.uniq
    #at some point we want to be sorting these on the date of the most recent child messare
  end
end

app/views/conversations/_message_link.html.slim
.message-user
  
  - if conversation.recipient_id == -1
    | message from system admin
  - elsif conversation.user_id == current_user.id
    | message with
    =link_to "@#{User.find(conversation.recipient_id).username}", profile_path(User.find(conversation.recipient_id).username)
  - else
    | message with
    =link_to "@#{conversation.user.username}", profile_path(conversation.user.username)
.message-date
  =time_ago_in_words(conversation.messages.first.created_at)
  | ago
.message-text
  -if conversation.unread_message_count(current_user) > 0
    =link_to conversation_path(conversation), :remote=>:true, :class => 'message-name', :"data-count"=> conversation.unread_message_count(current_user) do
      = conversation.messages.first.body
  -else
    =link_to conversation_path(conversation), :remote=>:true, :class => 'message-title' do
      = conversation.messages.first.body

app/views/conversations/_message_list.html.slim
- conversations.each do |conversation|
  div id="message-link-#{conversation.id}" 
    .message-item.clearfix class=cycle("odd", "even") 
      =render :partial => 'message_link',:locals => {conversation:conversation}

app/views/conversations/_message_thread.html.slim
h5.padless
  
  - if conversation.recipient_id == -1
    | message from system admin
  - elsif conversation.user_id == current_user.id
    | Message with
    =link_to "@#{User.find(conversation.recipient_id).username}", profile_path(User.find(conversation.recipient_id).username)
  - else
    | message with
    =link_to "@#{conversation.user.username}", profile_path(conversation.user.name)

- unless conversation.recipient_id == -1
  .message-reply
    
    = form_for :conversation_message, :remote => true, :url => conversation_messages_path(conversation) do |f|
      = f.hidden_field :conversation_id, :value => conversation.id
      .formrow
        
        = f.text_area :body, :autofocus => true, :id=>"message-body", :placeholder => 'type your new message here'
      = f.submit 'reply', :id => "send-message-button", :class => "button tiny"
.message-conversation
  = render conversation.messages

app/views/conversations/_message_user.html.slim
.modal
  .modal-heading
  	=link_to "x", "#close", :class => "close"
    h3 message #{@user.username}
  .modal-body
    =form_for :offer, :url => conversations_path, :html => {:id => "message-form"} do |f|
      = f.text_area :text, :id => 'text', :name => 'text', :class => 'message-form',:placeholder => "say something PRIVATELY to @#{@user.username}"
      input type='hidden' name='user_id' value="#{@user.id}" 
      .modal_button
      = f.submit 'Send Message'
             
javascript:
  $('textarea.message-form').focus(function () {
    $(this).animate({ height: "8em" }, 500); 
  });  

app/views/conversations/_new_message.html.haml
#new-message.reveal-modal{"data-reveal" => ""}
  .modal_heading
    %h2 new message
  .modal_body
    #select-recipient
      %p who would you like to message?
      %input#search_people{:type=>'text', :placeholder => 'type a user name',:style=>"width: 95%; margin-top: 10px;"}
        #search_result
    #message-text{:style=>"display:none;"}
      =form_for :offer, :url => conversations_path,:html => {:id => "message-form"} do |f|
        = f.text_area :text, :id => 'text', :name => 'text', :class => 'message-form',:placeholder => 'say something PRIVATELY to this user'
        %input{:type => 'hidden', :name => 'user_id', :id => 'user-id'}
        .modal_button
        = f.submit 'Send Message', :class => "button"
  %a.close-reveal-modal ×

:javascript
  function setClickBehavior() {
    $('.username').click(function() {
      if($(this).data("username") == "#{current_user.username}") {
        $.notification({ message:"you can't message yourself, silly user" });
        $('#search_result').empty();
        $('#search_people').val('');
      }
      else {
        console.log($(this));
        console.log($(this).data);
        $('#user-id').val($(this).data("user"));
        $('#search_people').val($(this).data("username"));
        $('#search_result').empty();
        $('#message-text').css("display","block");
        $('#text').attr('placeholder','send a message to @' + $(this).data("username"));
        $('#text').focus();
      }

    });
  };

  $(document).ready(function() {
    $('#search_people').focus();
    $('textarea.message-form').focus(function () {
      $(this).animate({ height: "8em" }, 500);
    });
    $('#search_people').click(function() {
      $(this).select();
    });


  jQuery(function(){
      jQuery('input#search_people')
        .data('timeout', null)
        .keyup(function(){
            clearTimeout(jQuery(this).data('timeout'));
            jQuery(this).data('timeout', setTimeout(function(){

             //timeout function
             $.post('/users/autocomplete', { q: $("input#search_people").val()}, function(data) {

                Jaml.register('user', function(user) {
                  a({href: ("#"), cls: "username", "data-user": user.user.id, "data-username": user.user.username},
                    div(
                      img({src: '/assets/profile.svg'}),
                      span(user.user.username)
                      )
                    )
                  div({cls: "clearboth"})
                });



                 if(data.length > 0){
                  console.log('gggggg');
                  $("#search_result").show();
                   $("#search_result").html("people matching '"+ $("input#search_people").val() + "'")
                   $(data).each(function(idx, d){
                     $("#search_result").append(Jaml.render('user',d));
                     setClickBehavior();
                   })
                 }else{
                   $("#search_result").html("no result")
                 }

                 }, "json");

            //timeout function

            }, 500));
        });
    });

  });

app/views/conversations/_offer.html.haml
- @offer.messages.each do |message|
  .offer_rpt
    = UserDecorator.new(message.user).linked_profile_pic('40')
    = message.body
  .clear

%a{:href => "#", :class => 'toggle-offer-reply'} reply

.offer_reply_form.hidden
  = form_for :offer_message, :url => offer_offer_messages_path(@offer) do |f|
    = f.hidden_field :offer_id, :value => @offer.id
    .formrow
      = f.text_area :body
    .formrow
      = f.submit 'reply'

app/views/conversations/broadcast.html.haml
%h2 new broadcast
#message-text
  =form_for :offer, :url => send_broadcast_path,:html => {:id => "message-form"} do |f|
    = f.text_area :text, :id => 'text', :name => 'text', :class => 'message-form',:placeholder => 'say something PRIVATELY to this user'
    %input{:type => 'hidden', :name => 'user_id', :id => 'user-id'}
    = f.submit 'Send Message'  

app/views/conversations/create.js.haml
$.notification({ message:"great, that worked", type:"#{type}" });

app/views/conversations/index.html.slim
.row
	.large-6.columns
		h3 Message Archives
	.large-6.columns
		button.large.right.new
			| + message
#messages
	div.row
		div.large-8.columns
			div#message 
				h4.padless
				- if @conversations.empty?
					| You have no messages
				- else
					= render :partial => 'message_thread', :locals => {conversation:@loaded_conversation}
		div.large-4.columns
			-unless @conversations.empty?
				#message-list
				= render :partial => 'message_list',:locals => {conversations:@conversations}

javascript:
	$(document).ready(function() {

		$(".new").click(function() {
			$('body').append("#{escape_javascript( render :partial => 'new_message')}");
			$('#new-message').foundation("reveal","open");
		});
	});	
  

  

app/views/conversations/show.html.haml
=content_for :head do
  = stylesheet_link_tag "offers"

=content_for :page_title do
  = image_tag 'messages.svg', :width => "25px",:height => "auto"
  %h1 
    =link_to 'Your Messages', user_offers_path(current_user.display_name)
    with
    -if @offer.user_id == current_user.id
      = @item ? @item.user.display_name : @offer.notifications.first.receiver.display_name
    -else
      = link_to @offer.user.display_name, profile_path(@offer.user.display_name)

    - if @item
      about
      = link_to @item.title, polymorphic_path(@item)
  .page_sub_heading
    An archive of the various private conversations you've had with other users about content on the site.


.message-reply
  
  = form_for :offer_message, :remote => true, :url => conversation_messages_path(@offer) do |f|
    = f.hidden_field :offer_id, :value => @offer.id
    .formrow
      
      = f.text_area :body, :autofocus => true, :id=>"message-body", :placeholder => 'type your new message here'
    = f.submit 'Send Message', :id => "send-message-button", :class => "green-button"
.message-thread
  = render @offer.messages    
  
:javascript
  $("#message-body").animate({ scrollTop: $('#message-body')[0].scrollHeight}, 1000);
  $("#send-message-button").click(function(e) {
    e.preventDefault();
    console.log($(this).context.value);
    $(this).context.value = "sending"
    $(this).context.disabled = true;
    $(this).submit();
  });
  

app/views/conversations/show.js.haml
$('#message').empty();
$('#message').html("#{escape_javascript render :partial => 'message_thread', :locals => {offer:@offer}}");
$('#message-link-#{@offer.id} .message-item').html("#{escape_javascript render :partial => 'message_link', :locals => {offer:@offer}}");
$.get("/users/check_notifcations");
$('html, body').animate({'scrollTop':   $('#bottom').offset().top}, 1000);