config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :controllers => { :registrations => "registrations", :sessions => "sessions",omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, :only => [:edit, :update, :index] do
    resources :conversations, :only => :index
    get 'notifications'
    post 'upload_file'
    collection do
      post 'autocomplete'
    end
    resources :subscriptions, :only => [:create,:destroy,:index]
  end

  resources :comments, :only => [:create, :destroy]

  resources :game_improvements, :only => [:create, :destroy, :show]
  resources :games do
    resources :game_boards

  end

  resources :votes, :only => [] do
    collection do
      post 'up'
      post 'down'
    end
  end

  resources :board_suggestions, :only => [:create,:destroy, :show]
  resources :invitations, :only => [] do
    collection do
      post 'check'
    end
  end

  resources :game_boards do
    collection do
      get 'popular'
      get 'archives'
    end
  end

  resources :workspaces

  resources :posts do
    post 'create_or_destroy_reaction'
    post 'flag_vote'
    collection do
      get 'popular'
      get 'familiar'
      get 'subscriptions'
      get 'user_games'
      get 'flagged'
      get 'autocomplete_tag_search'
    end
    member do
      post 'create_or_destroy_reaction'
    end
  end

  resources :conversations, :only => [:create,:show,:index, :destroy] do
    resources :messages, :only => [:create]
  end

  root 'pages#home'
  get '/pages/:page_name' => 'pages#index', :as => :pages
  get '/posts/:category/:tag' => 'posts#index', :as => :filtered_posts
  get '/sitemap.xml' => 'pages#sitemap'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/search' => 'users#search', via: [:get]
  # This needs to stay at the bottom such that a user can't override a preset URL
  match '/:display_name', :controller => :users, :action => :show, :as => :profile, via: [:get]
  get "/stats/:type", :as => 'stats', :controller => :stats, :action => :index


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_about_menu.html.slim
=link_to pages_path(:page=>'about') do
	=icon('gear', '', class: 'fa-2x fa-fw inline side-pads')
	.label about us
=link_to pages_path(:page=>'contact') do
	=icon('user', '', class: 'fa-2x fa-fw inline side-pads')
	.label contact us
=link_to pages_path(:page=>'privacy') do
	=icon('heart', '', class: 'fa-2x fa-fw inline side-pads')
	.label privacy policy	

app/views/shared/_footer.html.haml
%footer.footer
  .row
    .small-12.medium-6.large-3.columns
      %p.logo
        %i.fi-shield
        Crazy Dancing Guy
      %p.footer-links
        =link_to "About", pages_path("about")
        =link_to "How it Works", pages_path("how-it-works")
        =link_to "Privacy Policy", pages_path("privacy")
        =link_to "Contact Me", '/contact-us'
        -if user_signed_in?

          = link_to "Log out", destroy_session_path(:user), :method => :delete

    .small-12.medium-6.large-4.columns
      %p.logo Socialize with us
      %ul.contact
        %li
          %p
            %i.fi-social-facebook>
            =link_to 'facebook.com/CrazyDancingGuy', 'http://facebook.com/CrazyDancingGuy'
        %li
          %p
            %i.fi-social-twitter>
            =link_to 'twitter.com/CrazyDancingGuy', 'http://twitter.com/CrazyDancingGuy'

    .small-12.medium-6.large-5.columns

      %ul.hashtags
        %h3=link_to '@crazydancingguy',"http://crazydancingguy.com"
        %li=link_to '#climatejustice', 'https://twitter.com/hashtag/climatejustice'
        %li=link_to '#socialjustice', 'https://twitter.com/hashtag/socialjustice'
        %li=link_to '#genderequality', 'https://twitter.com/hashtag/genderequality'
      %hr
      .footer-links{:style=>'text-align:center;'}
        =link_to "Play With Your Mind", "http://playwithyourmind.com"
        =link_to "Presidential Election Games", "http://presidentialelectiongames.com"
        =link_to "The Keyboard Playground", "http://freeonlinetypinggames.com"
        =link_to "Good Luck Test", "http://goodlucktest.com"

#login.reveal-modal.remove-whitespace{"data-reveal" => ""}
  .row
    .large-6.columns.auth-plain
      .signup-panel.left-solid
        %p.welcome Registered Users
        %form#login-form
          .row.collapse
            .small-2.columns
              %span.prefix
                %i.fi-torso-female
            .small-10.columns
              %input{:placeholder => "username", :type => "text", :id =>'login-username'}
          .row.collapse
            .small-2.columns
              %span.prefix
                %i.fi-lock
            .small-10.columns
              %input{:placeholder => "password", :type => "password", :id => 'login-password'}
        %a.button{:href => "#",:id=>'login-button'} Log In
    .large-6.columns.auth-plain
      .signup-panel.newusers
        %p.welcome No account... yet?
        %p Why not sign up and exercise your first ammendment right to have some fun?  It's easy!
        =link_to new_user_registration_path, :class=>'button' do
          Sign Up
  %a.close-reveal-modal ×

#new-post.reveal-modal{"data-reveal" => ""}
  #form
  %a.close-reveal-modal ×

:javascript

  $('#login-button').on('click', function() {
    var data = {
      user: {login: $('#login-username').val(), password: $('#login-password').val(), remember_me: '1'}
    }

    $.ajax({ url: '/users/sign_in',
      type: 'POST',
      headers: {
          'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
        },
      data: data,
      success: function(response) {
        $('#login').foundation('reveal','close');
        $('.menu ul.inline-list').empty();
        setTimeout(function() {
           $('.menu ul.inline-list').html('#{escape_javascript render :partial=>"users/header_menu"}');
           window.location = '#{root_path}';
        }, 1000);


      },
      error: function(xhr, status, error) {
          alert(xhr.responseText);
       }
    });
  });

  $( document ).on('keyup','.autocomplete', function() {
      if($(this).val().length > 2) {
        $.get('#{autocomplete_tag_search_posts_path}',{q:$(this).val()}, function(data) {
          $('.autocomplete-options').empty();
          $('.autocomplete-options').show();
          $.each(data, function(index,value) {
            console.log(index,value);
            $('.autocomplete-options').append('<div class="autocomplete-option">'+value.name+'</div>');
          });

        });
      }
      else {
        $('.autocomplete-options').empty();
        $('.autocomplete-options').hide();
      }
  });

  $( document ).on( 'click', '#submit-post', function () {
      $('#post_tag_list').val('');
      $.ajax({ url: '/posts',
        type: 'POST',
        headers: {
            'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
          },
        data: $('#post-form').serializeArray()
      });
  });

  $( document ).on( 'click', '.autocomplete-option', function () {
    $('#tag-list').append('<div class="tag" value="' + $(this).text() + '">' + $(this).text() + '<div class="del">X</div></div>');
    $('.autocomplete-options').empty();
    $('.autocomplete-options').hide();
    str = ''
    $('#tag-list').find('.tag').each(function() {

      str += $(this).attr("value") + ',';
    });
    str = str.substring(0,str.length-1);
    $('#post_tag_list').val(str);
    setTimeout(function(){
        $('.autocomplete').val('');
        $('.autocomplete').focus();

    }, 100);
  });
  $( document ).on( 'click', '.del', function (event) {
    $(event.target).parent().remove();

    str = ''
    $('#tag-list').find('.tag').each(function() {
      console.log('in');
      str += $(this).attr("value") + ',';
    });
    str = str.substring(0,str.length-1);
    $('#post_tag_list').val(str);
    $('.autocomplete').focus();
  })

app/views/shared/_games_menu.html.slim
=link_to games_path do
	i.fi-star
	.label meet the games
=link_to game_boards_path do
	i.fi-star
	.label current challenges
=link_to archives_game_boards_path do
	i.fi-star
	.label archives	

app/views/shared/_head.html.haml
.contain-to-grid.fixed
  %nav.top-bar{"data-topbar" => "", :role => "navigation"}
    %ul.title-area
      %li
        %h1
          .hide-for-small
            %b.fi-star{:style=>"font-size: 30px;position:relative;top:3px;  margin-right: 4px;margin-left: 8px;"}
            =link_to 'witzi', root_path
          .show-for-small-only

            =link_to root_path do
              %b.fi-star{:style=>"font-size: 30px;position:relative;top:3px;  margin-right: 4px;margin-left: 8px;"}
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span Menu
    %section.top-bar-section
      %ul
        %li.divider
        %li.has-dropdown.small-dropdown
          %a{:href => "#"}
            %b.blue-green-text.fi-puzzle
            games
          %ul.dropdown.m-menu
            %li.blue-green-on-hover
              =link_to games_path do
                %b.fi-puzzle
                meet the games
            %li.blue-green-on-hover
              =link_to game_boards_path do
                %b.fi-play
                current challenges
            %li.blue-green-on-hover
              =link_to archives_game_boards_path do
                %b.fi-star
                archives
        %li.divider
        %li.has-dropdown.small-dropdown
          %a{:href => "#"}
            %b.green-text.fi-results
            posts
          %ul.dropdown.m-menu
            %li.green-on-hover
              =link_to posts_path do
                %b.fi-results
                all posts
            %li.green-on-hover
              =link_to popular_posts_path do
                %b.fi-heart
                popular
            -if user_signed_in?
              %li.green-on-hover
                =link_to user_games_posts_path do
                  %b.fi-star
                  your posts
              %li.green-on-hover
                =link_to subscriptions_posts_path do
                  %b.fi-star
                  by users you follow
              %li.green-on-hover
                =link_to familiar_posts_path do
                  %b.fi-star
                  familiar users
            %li.green-on-hover
              =link_to flagged_posts_path do
                %b.fi-star
                flagged

        %li.divider
        %li.has-dropdown.small-dropdown
          %a{:href => "#"}
            %b.red-text.fi-trophy
            stats
          %ul.dropdown.m-menu
            %li.red-on-hover
              =link_to stats_path('yesterday') do
                %b.fi-star
                yesterday's leaderboard
            %li.red-on-hover
              =link_to stats_path('week')  do
                %b.fi-star
                this week's leaderboard
            %li.red-on-hover
              =link_to stats_path('month')  do
                %b.fi-star
                this month's leaderboard
            %li.red-on-hover
              =link_to stats_path('overall')  do
                %b.fi-star
                all-time leaderboard

        %li.divider
        %li.has-dropdown.small-dropdown
          %a{:href => "#"}
            %b.light-blue-text.fi-torsos
            users
          %ul.dropdown.m-menu
            %li.light-blue-on-hover
              =link_to users_path do
                %b.fi-star
                explore users
            %li.light-blue-on-hover
              =link_to users_path  do
                %b.fi-star
                people you follow
            %li.light-blue-on-hover
              =link_to users_path  do
                %b.fi-star
                popular users


      %ul.right
        -if user_signed_in?
          %li
            =link_to profile_path(current_user.username), :class=> "personal-menu blue-green-text" do
              %i.fi-torso
          %li
            = link_to user_conversations_path(current_user), :class=> "green-text messages-menu" do
              %i.fi-mail
          %li
            = link_to user_notifications_path(current_user.username),:class=> "red-text notifications-menu" do
              %i.fi-alert
          %li
            = link_to edit_user_path(current_user), :class=> "light-blue-text about-menu" do
              %i.fi-widget
        -else
          %li
            %a{"data-reveal-id" => "login", :href => "#"} Login
          %li.divider
          %li
            =link_to 'Signup', new_user_registration_path


  #mobile-login.show-for-small-only
    %ul
      -if user_signed_in?

      -else
        %a{"data-reveal-id" => "login", :class=>'button tiny',:href => "#"} Login
        =link_to 'Signup', new_user_registration_path, :class=>'button tiny'

app/views/shared/_personal_menu.html.slim
=link_to profile_path(current_user.name) do
	=icon('heart', '', class: 'fa-2x fa-fw inline side-pads')
	.label profile
=link_to edit_user_path(current_user) do
	=icon('gear', '', class: 'fa-2x fa-fw inline side-pads')
	.label settings
=link_to destroy_user_session_path, :method => :delete do
	=icon('user', '', class: 'fa-2x fa-fw inline side-pads')
	.label logout

app/views/shared/_posts_menu.html.slim
=link_to posts_path do
	i.fi-star
	.label all posts
=link_to popular_posts_path do
	i.fi-star
	.label popular posts	
-if user_signed_in?
	=link_to user_games_posts_path do
		i.fi-star
		.label from games you've played
	=link_to subscriptions_posts_path do
		i.fi-star
		.label by users you follow	
	=link_to familiar_posts_path do
		i.fi-star
		.label by other users you know	
=link_to flagged_posts_path do
	i.fi-star
	.label flagged posts

app/views/shared/_settings_menu.html.slim
=link_to posts_path do
	=icon('gear', '', class: 'fa-2x fa-fw inline side-pads')
	.label meet the games
=link_to popular_posts_path do
	=icon('user', '', class: 'fa-2x fa-fw inline side-pads')
	.label current challenges
=link_to posts_path do
	=icon('heart', '', class: 'fa-2x fa-fw inline side-pads')
	.label archives	

app/views/shared/_sidebar.html.slim
nav.main-menu
  ul
    li
      a href="#" 
        =icon('dashboard', '', class: 'large-icon')
        span.nav-text
          | Your Dashboard
    li.has-subnav
      =link_to game_boards_path do
        =icon('puzzle-piece', '', class: 'large-icon')
        span.nav-text
          | Current Games
    li.has-subnav
      =link_to posts_path do 
        =icon('file', '', class: 'large-icon')
        span.nav-text
          | Submissions
    li
      =link_to stats_path do
        =icon('trophy', '', class: 'large-icon')
        span.nav-text
          | Results
    li.has-subnav
      =link_to users_path do 
        =icon('users', '', class: 'large-icon')
        span.nav-text
          | Explore Users

app/views/shared/_stats_menu.html.slim
=link_to top_yesterday_path do
	i.fi-star
	.label yesterday's leaderboard
=link_to top_week_path do
	i.fi-star
	.label this week's leaderboard
=link_to top_month_path do
	i.fi-star
	.label this month's leaderboard
=link_to stats_path do
	i.fi-star
	.label all-time leaderboard	
		

app/views/shared/_topbar.html.slim
#topbar
	#content-menu
		ul.right
	      	li= link_to games_path, :class=> "light-blue games-menu" do
	      		i.fi-star
	      	li= link_to posts_path, :class=> "red posts-menu" do
	      		i.fi-star
	      	li= link_to stats_path, :class=> "green stats-menu" do
	      		i.fi-star
	      	li= link_to users_path, :class=> "blue-green users-menu" do
	      		i.fi-star
	#games-menu.light-blue.games-menu
		=render 'shared/games_menu'
	#posts-menu.red.posts-menu
		=render 'shared/posts_menu'
	#stats-menu.green.stats-menu
		=render 'shared/stats_menu'
	#users-menu.blue-green.users-menu
		=render 'shared/users_menu'				
	#logo
		= link_to root_path
			=image_tag('game-logo.png')
		
	-if user_signed_in?
		#user-menu
			ul.right
		      	li= link_to profile_path(current_user.name), :class=> "personal-menu blue-green" do
		      		i.fi-star
		      	li= link_to user_conversations_path(current_user), :class=> "green messages-menu" do
		      		i.fi-star

		      	li= link_to user_notifications_path(current_user.name),:class=> "red notifications-menu" do
		      		i.fi-star

		      	li= link_to edit_user_path(current_user), :class=> "light-blue about-menu" do
		      		i.fi-star
     

		#messages-menu.green.messages-menu
			=render 'users/messages_window'
		#notifications-menu.red.notifications-menu
			=render 'users/notifications_window'
		#personal-menu.blue-green.personal-menu
			=render 'shared/personal_menu'
		#about-menu.light-blue.about-menu
			=render 'shared/about_menu'
	

										
	-else
		=link_to new_user_session_path
			#login-button
				button.light-blue.small login/signup							
		

app/views/shared/_users_menu.html.slim
=link_to users_path do
	i.fi-star
	.label explore users
=link_to users_path do
	i.fi-star
	.label people you follow	
=link_to users_path do
	i.fi-star
	.label popular users			