config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    :controllers => { :registrations => "registrations", :sessions => "sessions",omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, :only => [:edit, :update, :index] do
    resources :conversations, :only => :index
    get 'notifications'
    post 'upload_file'
    collection do
      post 'autocomplete'
    end
    resources :subscriptions, :only => [:create,:destroy,:index]
  end

  resources :comments, :only => [:create, :destroy]

  resources :game_improvements, :only => [:create, :destroy, :show]
  resources :games do
    resources :game_boards

  end

  resources :votes, :only => [] do
    collection do
      post 'up'
      post 'down'
    end
  end

  resources :board_suggestions, :only => [:create,:destroy, :show]
  resources :invitations, :only => [] do
    collection do
      post 'check'
    end
  end

  resources :game_boards do
    collection do
      get 'popular'
      get 'archives'
    end
  end

  resources :workspaces

  resources :posts do
    post 'create_or_destroy_reaction'
    post 'flag_vote'
    collection do
      get 'popular'
      get 'familiar'
      get 'subscriptions'
      get 'user_games'
      get 'flagged'
      get 'autocomplete_tag_search'
    end
    member do
      post 'create_or_destroy_reaction'
    end
  end

  resources :conversations, :only => [:create,:show,:index, :destroy] do
    resources :messages, :only => [:create]
  end

  root 'pages#home'
  get '/pages/:page_name' => 'pages#index', :as => :pages
  get '/posts/:category/:tag' => 'posts#index', :as => :filtered_posts
  get '/sitemap.xml' => 'pages#sitemap'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/search' => 'users#search', via: [:get]
  # This needs to stay at the bottom such that a user can't override a preset URL
  match '/:display_name', :controller => :users, :action => :show, :as => :profile, via: [:get]
  get "/stats/:type", :as => 'stats', :controller => :stats, :action => :index


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :user
  #has_many :email_digests, :dependent => :destroy

  validates_uniqueness_of :subscription_id, :scope => [:user_id, :subscription_type]



  validate :valid_subscription



  #after_save :update_importance
  #scope :in_country, lambda {|country| joins(:locations).where('locations.country = ?',country)}

  scope :users, lambda { |user| {
    :conditions => { :user_id => user.id, :subscription_type => 'user' }
  } }

  private
  def self.count_by_day(cutoff_at)
    result = count(:all, :conditions => ["created_at >= ?", cutoff_at],
                         :group => "DATE(created_at)")
    # See http://ruby-doc.org/core-1.8.7/classes/Hash.html#M000163
    result.default = 0
    result
  end

  def valid_subscription
    errors.add(:subscription_id, "you can't follow yourself") if subscription_id == user_id
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # authorize_resource :only => :destroy
  before_filter :load_resource, :only => :destroy
  before_filter :authenticate_user!, :only => [:create, :destroy]
  


  def index
 
    @subscriptions = current_user.subscriptions
    @page_title = "Your subscriptions list"
    user_ids = @subscriptions.map(&:subscription_id)
    @posts = Post.where('user_id in (?)',user_ids)
  end

  def create
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @subscription = Subscription.new(:subscription_id => params[:user_id],:subscription_type => "user", :user => User.find(current_user.id))
      if @subscription.save
        #current_user.subscriptions << @subscription
        respond_to do |format|
          format.js 
        end
      else
        respond_to do |format|
          format.json { render json: {error:{msg:"you have already added that tag as an subscription"}}, status: :unprocessable_entity }
        end 
      end      
    end
  end


  def destroy
    @counter=@subscription.id
    @subscription.destroy
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.js {}
    end
  end


  private
  def load_resource
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_follow_user.html.haml
#follow-button
	=link_to user_subscriptions_path(@user,:subscription_id => @user.id), :remote=> :true, :method => "post" do
		%button.small follow wombat

app/views/subscriptions/_follow_user.html.slim
#follow-button
	=link_to user_subscriptions_path(@user,:subscription_id => @user.id), :remote=> :true, :method => "post" do
		button.small follow #{@user.name}	

app/views/subscriptions/_unfollow_user.html.haml
#follow-button
	=link_to user_subscription_path(@user, @subscription.id), :remote=> :true, :method => "delete" do
		%button.small unfollow #{@user.username}

app/views/subscriptions/_unfollow_user.html.slim
#follow-button
	=link_to user_subscription_path(@user, @subscription.id), :remote=> :true, :method => "delete" do
		button.small unfollow #{@user.name}	

app/views/subscriptions/create.js.slim
|
	$.notification({ message:"ok, you are now following #{@user.username}", type:"success" });
	$('#follow-button').html("#{j render :partial => 'subscriptions/unfollow_user'}");

app/views/subscriptions/destroy.js.slim
|
	$.notification({ message:"you are no longer following #{@user.username}", type:"success" });
	$('#follow-button').html("#{j render :partial => 'subscriptions/follow_user'}")

app/views/subscriptions/index.html.slim
#container.large-12.columns.transitions-enabled.large-centered.clearfix
	-@posts.each do |p|
		=render :partial => 'posts/feed_layout', :locals => {:post => p}